# Generated by Django 4.1.10 on 2023-07-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товары в заказе'},
        ),
    ]
